# Generated by Django 5.2.6 on 2025-11-05 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_create_projects_sqlite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presupuesto',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'managed': True},
        ),
    ]
