# Generated by Django 5.2.6 on 2025-11-05 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subcontractors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrato',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='subcontratista',
            options={'managed': True},
        ),
    ]
