# Generated by Django 5.2.6 on 2025-11-05 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={'managed': True},
        ),
    ]
