# Generated by Django 5.2.6 on 2025-11-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoTecnico',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, db_comment='Plano/Render/Fotograf�a/Informe', max_length=100, null=True)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_carga', models.DateField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'documento_tecnico',
                'managed': False,
            },
        ),
    ]
