# Generated by Django 5.2.6 on 2025-11-05 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventario',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='inventariomaterial',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='proveedormaterial',
            options={'managed': True},
        ),
    ]
