# Generated by Django 5.2.6 on 2025-10-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificacion',
            fields=[
                ('id_certificacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'certificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id_incidente', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('gravedad', models.CharField(blank=True, db_comment='Baja/Media/Alta/Cr�tica', max_length=50, null=True)),
                ('fecha', models.DateField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'incidente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id_inspeccion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('resultado', models.CharField(blank=True, db_comment='Cumple/No Cumple', max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inspeccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PruebaCalidad',
            fields=[
                ('id_prueba', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('resultado', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prueba_calidad',
                'managed': False,
            },
        ),
    ]
