# Generated by Django 5.2.6 on 2025-11-05 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quality', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificacion',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='incidente',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='inspeccion',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pruebacalidad',
            options={'managed': True},
        ),
    ]
