# Generated by Django 5.2.6 on 2025-11-05 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0002_create_cliente_sqlite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': True},
        ),
    ]
